# Site config
name: oscarb.se
description: To teach, design and program!
url: http://oscarb.github.io
baseurl: /
# author
# logo
# social

# Jekyll config
markdown: kramdown
sass:
  style: expanded
gems:
  - jekyll-seo-tag
