# Site config
name: oscarb.se
description: To teach, design and program!
url: http://oscarb.github.io
baseurl:
colors:
  primary: '#184b81'
  accent: '#18814f'

# author
# logo
# social

# Jekyll config
markdown: kramdown
sass:
  style: expanded
gems:
  - jekyll-seo-tag
