# Site config
name: oscarb.se
description: Teacher, Android developer and UX designer
url: http://oscarb.github.io
baseurl:

author: oscarb
logo: /images/logo-transparent-blue.png
# social

# Jekyll config
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-seo-tag
  - jekyll-sitemap


# compress config
compress_html:
  clippings: all
  comments: [" <!-- ", " --> "]
