# Site config
name: oscarb.se
title: oscarb.se
description: Teacher, Android developer and UX designer
keywords: [teacher, developer, designer, android, education, technology, design]
url: https://www.oscarb.se
baseurl:

repository: oscarb/oscarb.github.io

author: oscarb
logo: /images/logo-transparent-blue.png

social:
  links:
    - http://se.linkedin.com/in/oscarbjorkman/
    - https://github.com/oscarb

# Jekyll config
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-seo-tag
  - jekyll-sitemap


# compress config
compress_html:
  clippings: all
  comments: [" <!-- ", " --> "]
