# Site config
name: oscarb.se
description: To teach, design and program!
colors:
  primary: '#184b81'
  accent: '#18814f'

# url: oscarb.se
# author
# logo
# social

# Jekyll config
markdown: kramdown
sass:
  style: expanded
gems:
  - jekyll-seo-tag
