# Site config
name: oscarb.se
description: To teach, design and program!
# url: oscarb.se
# author
# logo
# social

# Jekyll config
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-seo-tag
